function(baron_read_version path)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    file(READ "${path}" baron_version_json)
    string(REGEX MATCH "\"version\"[ \t\r\n]*:[ \t\r\n]*\"([0-9]+\.[0-9]+\.[0-9]+)\"" found "${baron_version_json}")
    if(NOT found)
        message(FATAL_ERROR "Missing Baron version in ${path}")
    endif()
    set(BARON_VERSION "${CMAKE_MATCH_1}" PARENT_SCOPE)
    string(REGEX MATCH "\"version_code\"[ \t\r\n]*:[ \t\r\n]*([0-9]+)" found "${baron_version_json}")
    if(NOT found)
        message(FATAL_ERROR "Missing Baron version_code in ${path}")
    endif()
    set(BARON_VERSION_CODE "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()
